# Introduction to PyTorch

<img src="pytorch.jpg" data-canonical-src="" width="500" height="400" />

1. Open source machine learning framework 

2. Python-based scientific computing package
    - A replacement for NumPy to use the power of GPUs
    - A deep learning research platform that provides maximum flexibility and speed

3. Deep Learning Library


## Three levels of Abstractions

1. Tensor
2. Variable
3. Module

### Tensor

- A multi-dimensional matrix containing elements of a single data type
- defines nine CPU tensor types and nine GPU tensor type


|Data type|dtype|CPU tensor|GPU tensor|
|---|---|---|---|
|32-bit floating point|torch.float32 or torch.float|torch.FloatTensor|torch.cuda.FloatTensor|
|64-bit floating point|torch.float64 or torch.double|torch.DoubleTensor|torch.cuda.DoubleTensor|
|16-bit floating point|torch.float16 or torch.half|torch.HalfTensor|torch.cuda.HalfTensor|
|8-bit integer (unsigned)|torch.uint8|torch.ByteTensor|torch.cuda.ByteTensor|
|8-bit integer (signed)|torch.int8|torch.CharTensor|torch.cuda.CharTensor|
|16-bit integer (signed)|torch.int16 or torch.short|torch.ShortTensor|torch.cuda.ShortTensor|
|32-bit integer (signed)|torch.int32 or torch.int|torch.IntTensor|torch.cuda.IntTensor|
|64-bit integer (signed)|torch.int64 or torch.long|torch.LongTensor|torch.cuda.LongTensor|
|Boolean|torch.bool|Torch.BoolTensor|torch.cuda.BoolTensor|


#### Import pytorch

In [1]:
import torch

In [2]:
print(torch.__version__)

1.3.0


#### Define a tensor

In [3]:
x = torch.tensor([[1, 1], [-1, 0]])
print(x)

tensor([[ 1,  1],
        [-1,  0]])


In [4]:
print(x.dtype)
print(type(x))

torch.int64
<class 'torch.Tensor'>


In [5]:
import numpy as np

In [6]:
arr = np.array([[1, 1], [-1, 0]])
print(arr)

[[ 1  1]
 [-1  0]]


How to convert numpy array to torch tensor?

In [7]:
torch.tensor(arr)

tensor([[ 1,  1],
        [-1,  0]])

In [8]:
torch.from_numpy(arr)

tensor([[ 1,  1],
        [-1,  0]])

Pytorch indexing

In [9]:
x[0]

tensor([1, 1])

In [10]:
x[0][1]

tensor(1)

In [11]:
y = torch.Tensor([2])

In [12]:
y.item() # To access a number from a tensor containing a single value

2.0

### Variable

- Node in a computation graph.
- Stores data and gradient.
- Supports all of operations defined on a Tensor.

In [13]:
import torch
from torch.autograd import Variable

In [14]:
N, D = 2, 2

In [15]:
x = Variable(torch.randn(N, D), requires_grad=True)
y = Variable(torch.randn(N, D), requires_grad=True)

In [16]:
a = 3*x + 2*y
b = torch.sum(a)
b.backward()

In [17]:
print(x.grad.data)
print(y.grad.data)

tensor([[3., 3.],
        [3., 3.]])
tensor([[2., 2.],
        [2., 2.]])


#### Module

- A neural network layer
- may store state or learnable weights

Layers
1. Convolutional layers
2. Pooling Layers
3. Loss functions
4. Other layers (Dropout, Linear, Normalization Layer)

#### Starting a new project

1. Data preparation
2. Model Design (Design your own model or use pretrained model)
3. Training strategy

##### Type of models
- MLPs
    - Regression 
    - Classification
- Convolutional Neural Network (CNN)